name: Deploy to firebase hosting on merge

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install firebase tools
        run: npm install -g firebase-tools

      - name: Build and test
        run: npm run lint && npm run build

      - name: Release
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
