name: Build firebase function

on:
  push:
    branches: [ feature/**, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and test
        run: |
          cd functions
          npm ci && npm run lint && npm run build
